name: Build Dev Environment
on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: |
          touch .env
          echo TOMTOM_API_KEY=${{ secrets.TOMTOM_API_KEY }} >> .env   

      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile    

      - name: Run test
        run: yarn test

      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}